# Generated by Django 6.1 on 2026-09-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_employee_all_zones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='allowed_shifts',
        ),
    ]
