# Generated by Django 6.1 on 2026-09-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_migrate_legacy_planning_records'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planningassignment',
            name='unique_planning_assignment_per_employee_date',
        ),
        migrations.RemoveConstraint(
            model_name='staffingrequirement',
            name='unique_staffing_requirement_per_weekday',
        ),
        migrations.RemoveConstraint(
            model_name='staffingrequirement',
            name='valid_staffing_weekday',
        ),
        migrations.RemoveField(
            model_name='staffingrequirement',
            name='company',
        ),
        migrations.RemoveField(
            model_name='staffingrequirement',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staffingrequirement',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='staffingrequirement',
            name='zone',
        ),
        migrations.DeleteModel(
            name='PlanningAssignment',
        ),
        migrations.DeleteModel(
            name='StaffingRequirement',
        ),
    ]
