# Generated by Django 6.1 on 2026-09-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0014_migrate_zone_requirements'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zoneshiftpositionrequirement',
            name='unique_position_per_zone_shift',
        ),
        migrations.RemoveConstraint(
            model_name='zoneshiftpreset',
            name='unique_zone_shift_preset_per_company',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='configured_shifts',
        ),
        migrations.RemoveField(
            model_name='zoneshiftpreset',
            name='company',
        ),
        migrations.RemoveField(
            model_name='zoneshiftpreset',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='zoneshiftpreset',
            name='zone',
        ),
        migrations.DeleteModel(
            name='ZoneShiftPositionRequirement',
        ),
        migrations.DeleteModel(
            name='ZoneShiftPreset',
        ),
    ]
